---
title: "MAGGIE and DOPAMINS @ REXUS/BEXUS Student Training Week"
date: 2026-01-26
---

MAGGIE and DOPAMINS are going to Esrange


With the successfull acceptance to the REXUS/BEXUS programm, both the MAGGIE and the DOPAMINS team were invited to the REXUS/BEXUS Student Training Week and the Preliminary Design Review (PDR) at Esrange (Kiruna/Sweden). This will take place from 26 to 30 January 2026 up in the far and vast north of Sweden at the rocket launch facility Esrange. 

We are excited to present there on our experiments developments, but also see and meet other european teams, project ideas and students. We can also look forward to unique natural scenery and great chances of seeing the magnificent Northern Lights. 

With the submission of the first student experiment description of both teams a huge milestone was celebrated in advance of the TRaining Week. The next steps on the way to Kiruna are preparing presentations and getting ready for the cold weather up there.

We'll keep you up to date.